---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pac-pull-request-short-name-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        displayName: Task with no effect
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi10/ubi-micro
              workingDir: $(workspaces.source.path)
              script: |
                echo "Wow - This is working"
                exit 0
